title: "Reese Hamilton"
logo: "/images/Composite_headshot.jpg?raw=true" # Your photo or logo here
description: "Reese Hamilton Portfolio"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Uncomment and add your Google Analytics tracking ID below if you have one
# google_analytics: UA-000000-0

# Social links configuration for the minimal theme
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/rahamilton19"
    icon: "fab fa-linkedin"

show_social_links: true # Add this line if the theme requires it


