title: "Reese Hamilton"
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > 
  Reese Hamilton Data Science Portfolio  
  Willamette University Master of Science in Data Science

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Uncomment and add your Google Analytics tracking ID below if you have one
# google_analytics: UA-000000-0

# Add your social links or other configuration options below
# For example, to add a LinkedIn link:
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/rahamilton19"
    icon: "fab fa-linkedin"
